import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, { useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import Card from './Card/Card';
import { weatherData } from '../public/Data/Data';
import City from './City/City';
import img from "../public/Img/wi.png";
import img1 from "../public/Img/art.jpg";



export default function Home({data}) {
  const[weda , setWeda] = useState("Yep");
  const s = data.hourly;


  // useEffect(() => {
  //   getWether();
  // })
  //   async function getWether(){
  //     const url = "https://api.openweathermap.org/data/2.5/weather?q=Detroit&appid=f20a93028b65bc332d4524357ee92487";
  //     fetch(url).then(response => 
  //       response.json().then(data => ({
  //           data: data,
  //           status: response.status
  //       })
  //     ).then(res => {
  //       // res.data.weather[0].main
  //       console.log(res.data)
  //       // setWeda(res.data.weather[0].main)
  //       let obj = {coord: res.data.coord.coord, weather: res.data.weather[0].weather, 
  //         base: res.data.weather[0].base, main : res.data.weather[0].main, visibility: res.data.weather[0].visibility };
  //         console.log(obj);
  //       setWeda(obj.main);
  //       return obj;
  //     }))
  //     };

  return (

    
    <div className="container-fluid">
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="container">
  <div className="row">
    <div className="col-12">
      <div>
        <nav className="navbar navbar-dark bg-primary">
          <div className="container">
            <a className="navbar-brand" href="#">
              <Image src={img} alt="weather1" width="30" height="24"/>
            </a>
        </div>
      </nav>
      </div>
    </div>
    </div>
  <div className="row">
    <div className="col-8">
      <div>
          <City/>
      </div>
    </div>
    <div className="col-4">
    <div className="container">
      <Image src={img1} alt="weather" width={300} height={300} />
        <div className="centered">Todays weather in focus</div>
    </div>
    </div>
  </div>
  <div className="row">
    <div className="col-12"><div className="row row-cols-1 row-cols-md-6 g-4" style={{margin :"5px"}}>
          {s.map((hourly, index) => { return <Card time={hourly.dt} temp={hourly.temp} fl={hourly.feels_like} key={index}/>})}
        {/* <Card data={data}/> */}
        {console.log(data)}
        </div></div>
  </div>
</div>
        
      </main>

      <footer classNameName={styles.footer}>
          <span classNameName={styles.logo}>
            <p>Weather app</p>
          </span>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const response = await fetch(
    "https://api.openweathermap.org/data/2.5/onecall?lat=33.44&lon=-94.04&exclude=minutely&appid=f20a93028b65bc332d4524357ee92487"
  );

  const data = await response.json();
  console.log(data);
  return {
    props: { data: data },
  };
}